src/Entity/Link.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Repository\LinkRepository;
use DateTimeImmutable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as Serializer;
use Ramsey\Uuid\Uuid;

#[ORM\Entity(repositoryClass: LinkRepository::class)]
#[ORM\Table(name: 'links')]
class Link
{
    /**
     * @var array<string>
     */
    #[Serializer\Exclude]
    public array $categoryAliases = [];
    #[ORM\Id]
    #[ORM\Column(type: 'guid')]
    private string $id;
    #[ORM\Column(type: 'text', nullable: false)]
    private string $url;
    #[ORM\Column(type: 'datetime_immutable', nullable: false)]
    private DateTimeImmutable $created;
    #[ORM\Column(type: 'boolean', options: [ 'default' => false ])]
    private bool $isPublic = false;
    #[ORM\OneToOne(mappedBy: 'link', targetEntity: LinkMetadata::class, cascade: [ 'persist', 'remove' ])]
    private ?LinkMetadata $metadata = null;
    /**
     * @var Collection<int,Category>
     */
    #[ORM\ManyToMany(targetEntity: Category::class, inversedBy: 'links', cascade: [ 'persist', 'remove' ])]
    #[ORM\JoinTable(name: 'categories2links')]
    #[Serializer\Type('ArrayCollection<Category>')]
    private Collection $categories;
    /**
     * @var Collection<int,Tag>
     */
    #[ORM\ManyToMany(targetEntity: Tag::class, inversedBy: 'links', cascade: [ 'persist', 'remove' ])]
    #[ORM\JoinTable(name: 'tags2links')]
    #[Serializer\Exclude]
    private Collection $tags;

    /**
     * @param array<Category> $categories
     * @param array<Tag> $tags
     */
    public function __construct(string $url, array $categories = [], array $tags = [], bool $isPublic = false)
    {
        $this->id = Uuid::uuid4()->toString();
        $this->url = $url;
        $this->isPublic = $isPublic;
        $this->created = new DateTimeImmutable('now');
        $this->categories = new ArrayCollection($categories);
        $this->tags = new ArrayCollection($tags);
    }

    public function getUrl(): string
    {
        return $this->url;
    }

    public function isPublic(): bool
    {
        return $this->isPublic;
    }

    /**
     * @return Collection<int,Category>
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function setCategoryAliases(mixed $categoryAliases): self
    {
        if (!is_array($categoryAliases)) {
            $categoryAliases = array_filter(array_map('trim', explode(',', strval($categoryAliases))));
        }

        $this->categoryAliases = $categoryAliases;

        return $this;
    }

    public function overrideCreated(DateTimeImmutable $created): void
    {
        $this->created = $created;
    }

    public function attachMetadata(LinkMetadata $metadata): void
    {
        $this->metadata = $metadata;
    }

    public function hasMetadata(): bool
    {
        return $this->metadata !== null;
    }

    public function getDomain(): string
    {
        return strval(parse_url($this->url, PHP_URL_HOST));
    }

    #[Serializer\VirtualProperty]
    public function getTitle(): ?string
    {
        return ($this->metadata !== null) ? $this->metadata->getTitle() : null;
    }

    #[Serializer\VirtualProperty]
    public function getDescription(): ?string
    {
        return ($this->metadata !== null) ? $this->metadata->getDescription() : null;
    }

    /**
     * @return array<string>
     */
    #[Serializer\VirtualProperty]
    #[Serializer\SerializedName('tags')]
    public function getTagStrings(): array
    {
        return $this->tags->map(fn (Tag $t): string => $t->getTag())->toArray();
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Welcome!{% endblock %}</title>
</head>
<body>
    {% block body %}{% endblock %}
</body>
</html>

templates/home.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>links.johnnoel.uk</h1>

    {% for category in categories %}
        <h2>{{ category.name }}</h2>
        <ul>
            {% for link in links|filter(l => category.slug in l.categoryAliases) %}
                <li>
                    <a href="{{ link.url }}" rel="nofollow noopener">{{ link.title|default(link.url) }}</a>{% if link.title is not empty %} ({{ link.domain }}){% endif %}
                    {% if link.description is not empty %}
                        <br>{{ link.description }}
                    {% endif %}
                    {% if not link.public %}
                        <div><span>private</span></div>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    {% endfor %}

    <h2>Uncategorised</h2>
    <ul>
        {% for link in links|filter(l => l.categoryAliases|length == 0) %}
            <li>
                <a href="{{ link.url }}" rel="nofollow noopener">{{ link.title|default(link.url) }}</a>{% if link.title is not empty %} ({{ link.domain }}){% endif %}
                {% if link.description is not empty %}
                    <br>{{ link.description }}
                {% endif %}
                {% if not link.public %}
                    <div><span>private</span></div>
                {% endif %}
            </li>
        {% endfor %}
    </ul>
{% endblock body %}

templates/link.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <h1>{{ form_type }} link</h1>
    {{ form_start(form) }}
    {{ form_row(form.url) }}
    {{ form_row(form.isPublic) }}
    {{ form_rest(form) }}
    <button type="submit">{{ form_type }} link</button>
    {{ form_end(form) }}
{% endblock body %}

templates/login.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {% if error %}
        <div>{{ error.messageKey|trans(error.messageData, 'security') }}</div>
    {% endif %}

    <form action="{{ path('login') }}" method="post">
        <label for="username">Email:</label>
        <input type="text" id="username" name="_username" value="{{ last_username }}">

        <label for="password">Password:</label>
        <input type="password" id="password" name="_password">

        <input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}">

        <button type="submit">login</button>
    </form>
{% endblock body %}